image: cirrusci/flutter:stable

stages:
  - analyze
  - test

analyze:
  stage: analyze
  script:
    - dart --version
    - pub get
    # TODO - dartanalyzer .

unit_test:
  stage: test
  script:
    - flutter --version
    - pub get
    - ./test.sh
