image: ghcr.io/cirruslabs/flutter:3.32.3

stages:
  - analyze
  - test

analyze:
  stage: analyze
  script:
    - dart --version
    - dart pub get
    - dart analyze

unit_test:
  stage: test
  script:
    - flutter --version
    - dart pub get
    - ./test.sh
