name: iop_sdk
description: SDK for Decentralized Access Control based on W3C standards to provide SSI with decentralized identifiers (DID), keys, rights and verifiable claims/credentials (VC).
documentation: https://developer.iop.global
homepage: https://iop.global
repository: https://github.com/Internet-of-People/morpheus-dart

version: 4.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  ffi: ^0.1.3
  http: ^0.12.1
  meta: ^1.1.8
  pedantic: ^1.9.0
  json_annotation: ^3.0.1
  json_serializable: ^3.3.0
  optional: ^5.0.0

dev_dependencies:
  build_runner: ^1.10.0
  test: ^1.15.1
  mockito: ^4.1.1

targets:
  $default:
    builders:
      json_serializable:
        options:
          nullable: false