name: iop_sdk
description: SDK for Decentralized Access Control based on W3C standards to provide SSI with decentralized identifiers (DID), keys, rights and verifiable claims/credentials (VC).
documentation: https://developer.iop.technology/
homepage: https://iop.global
repository: https://github.com/Internet-of-People/iop-dart

version: 5.0.0-alpha1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  ffi: ^1.0.0
  http: ^0.13.0
  meta: ^1.1.8
  pedantic: ^1.9.0
  json_annotation: ^4.0.0
  json_serializable: ^4.1.0

dev_dependencies:
  build_runner: ^1.12.2
  test: ^1.15.1
  mockito: ^5.0.0

targets:
  $default:
    builders:
      json_serializable:
        options:
          nullable: false